// utils/data-ait.js

export const aitParameter = [
  {
    id: 'A001',
    event: 'Angsuran',
    aitCode: 'F0000002',
    description: 'SETTLEMENT ANGSURAN',
  },
  {
    id: 'A002',
    event: 'Angsuran',
    aitCode: 'F0000003',
    description: 'OVERBOOK TO AR',
  },
  {
    id: 'A003',
    event: 'Cancel Angsuran',
    aitCode: 'F1000002',
    description: 'REVERSAL ANGSURAN',
  },
  {
    id: 'A004',
    event: 'Cancel Angsuran',
    aitCode: 'F1000003',
    description: 'OVERBOOK TO TITIPAN',
  },
  {
    id: 'A005',
    event: 'Pelunasan ET',
    aitCode: 'F0000004',
    description: 'PRETERM',
  },
  {
    id: 'A006',
    event: 'Pelunasan IC',
    aitCode: 'F0000005',
    description: 'KLAIM ASURANSI',
  },
  {
    id: 'A007',
    event: 'Cancel Pelunasan ET',
    aitCode: 'F1000004',
    description: 'CANCEL PRETERM',
  },
  {
    id: 'A008',
    event: 'Cancel Pelunasan IC',
    aitCode: 'F1000005',
    description: 'CANCEL CLAIM',
  },
  {
    id: 'A009',
    event: 'Repossess Asset Sold',
    aitCode: 'F0030002',
    description: 'SOLD REPO',
  },
]
export const aitParameterTransform = [
  {
    aitCode: 'F0000002',
    lineGt: 2,
    amountType: 'POKOK',
    isOptional: false,
  },
  {
    aitCode: 'F0000002',
    lineGt: 3,
    amountType: 'BUNGA',
    isOptional: false,
  },
  {
    aitCode: 'F0000003',
    lineGt: 2,
    amountType: 'POKOK',
    isOptional: false,
  },
  {
    aitCode: 'F0000003',
    lineGt: 3,
    amountType: 'BUNGA',
    isOptional: false,
  },
  {
    aitCode: 'F1000002',
    lineGt: 2,
    amountType: 'POKOK',
    isOptional: false,
  },
  {
    aitCode: 'F1000002',
    lineGt: 3,
    amountType: 'BUNGA',
    isOptional: false,
  },
  {
    aitCode: 'F1000003',
    lineGt: 2,
    amountType: 'POKOK',
    isOptional: false,
  },
  {
    aitCode: 'F1000003',
    lineGt: 3,
    amountType: 'BUNGA',
    isOptional: false,
  },
  {
    aitCode: 'F0000004',
    lineGt: 6,
    amountType: 'POKOK',
    isOptional: false,
  },
  {
    aitCode: 'F0000004',
    lineGt: 8,
    amountType: 'BUNGA',
    isOptional: false,
  },
  {
    aitCode: 'F0000005',
    lineGt: 6,
    amountType: 'POKOK',
    isOptional: false,
  },
  {
    aitCode: 'F0000005',
    lineGt: 8,
    amountType: 'BUNGA',
    isOptional: false,
  },
  {
    aitCode: 'F1000004',
    lineGt: 6,
    amountType: 'POKOK',
    isOptional: false,
  },
  {
    aitCode: 'F1000004',
    lineGt: 8,
    amountType: 'BUNGA',
    isOptional: false,
  },
  {
    aitCode: 'F1000005',
    lineGt: 6,
    amountType: 'POKOK',
    isOptional: false,
  },
  {
    aitCode: 'F1000005',
    lineGt: 8,
    amountType: 'BUNGA',
    isOptional: false,
  },
  {
    aitCode: 'F0030002',
    lineGt: 6,
    amountType: 'POKOK',
    isOptional: false,
  },
  {
    aitCode: 'F0030002',
    lineGt: 8,
    amountType: 'BUNGA',
    isOptional: false,
  },
  {
    aitCode: 'F0030002',
    lineGt: 10,
    amountType: 'DENDA',
    isOptional: true,
  },
  {
    aitCode: 'F0030002',
    lineGt: 1,
    amountType: 'SOLD',
    isOptional: true,
  },
  {
    aitCode: 'F0030002',
    lineGt: 2,
    amountType: 'SOLD',
    isOptional: true,
  },
  {
    aitCode: 'F0030002',
    lineGt: 17,
    amountType: 'EXPENSE',
    isOptional: true,
  },
  {
    aitCode: 'F0030002',
    lineGt: 18,
    amountType: 'EXPENSE',
    isOptional: true,
  },
]
