export const allFieldMapping = [
  // Required Fields (Y)
  {
    njfKey: 'JF_ADV_ARR',
    jsonKey: 'FUND_ADV_ARR',
    type: 'STRING',
    isRequired: true,
    description: 'Kode Advance (1 Advance & 2 Reguler)',
  },
  {
    njfKey: 'JF_BRANCH_CODE',
    jsonKey: 'FUND_BR_ID',
    type: 'STRING',
    isRequired: true,
    description: 'Kode cabang',
  },
  {
    njfKey: 'JF_COF',
    jsonKey: 'FUND_TOP_SEASONAL',
    type: 'NUMBER',
    isRequired: true,
    description: 'Term Of Payment Seasion',
  },
  {
    njfKey: 'JF_CONT_DATE',
    jsonKey: 'FUND_CONT_DATE',
    type: 'DATE',
    isRequired: true,
    description: 'Tanggal kontrak',
  },
  {
    njfKey: 'JF_CONT_NO',
    jsonKey: 'FUND_CONT_NO',
    type: 'STRING',
    isRequired: true,
    description: 'Nomor PK',
  },
  {
    njfKey: 'JF_COST_CENTER',
    jsonKey: 'COST_CENTER',
    type: 'STRING',
    isRequired: true,
    description: 'Cost center khusus untuk syariah (mapping SAP)',
  },
  {
    njfKey: 'JF_CUST_NAME',
    jsonKey: 'FUND_CUST_NAME',
    type: 'STRING',
    isRequired: true,
    description: 'Data Nama Nasabah',
  },
  {
    njfKey: 'JF_INIT_PRIN_AMNT',
    jsonKey: 'FUND_ADMF_PRIN',
    type: 'NUMBER',
    isRequired: true,
    description: 'Pokok Hutang ADMF',
  },
  {
    njfKey: 'JF_INSR_CODE',
    jsonKey: 'FUND_INSR_CODE',
    type: 'STRING',
    isRequired: true,
    description: 'Kode Asuransi',
  },
  {
    njfKey: 'JF_INT_RATE',
    jsonKey: 'FUND_ADMF_EFF_RATE',
    type: 'NUMBER',
    isRequired: true,
    description: 'Data rate COF kontrak',
  },
  {
    njfKey: 'JF_LOAN_DUE_DATE',
    jsonKey: 'FUND_DUE_DATE',
    type: 'DATE',
    isRequired: true,
    description: 'Tanggal Jatuh Tempo',
  },
  {
    njfKey: 'JF_LOAN_END_DATE',
    jsonKey: 'FUND_LAST_DATE',
    type: 'DATE',
    isRequired: true,
    description: 'Tanggal Angsuran Terakhir',
  },
  {
    njfKey: 'JF_LOAN_START_DATE',
    jsonKey: 'FUND_FIRST_DATE',
    type: 'DATE',
    isRequired: true,
    description: 'Tanggal Angsuran Pertama',
  },
  {
    njfKey: 'JF_LOAN_TENOR',
    jsonKey: 'FUND_ADMF_TOP',
    type: 'NUMBER',
    isRequired: true,
    description: 'Total Tenor ADMF',
  },
  {
    njfKey: 'JF_OBJT_BRAND',
    jsonKey: 'FUND_OBJT_BRAND',
    type: 'STRING',
    isRequired: true,
    description: 'Kode Brand',
  },
  {
    njfKey: 'JF_OBJT_CHASSIS_NO',
    jsonKey: 'FUND_OBJT_CHASIS_NO',
    type: 'STRING',
    isRequired: true,
    description: 'Nomor rangka',
  },
  {
    njfKey: 'JF_OBJT_CODE',
    jsonKey: 'FUND_OBJT_CODE',
    type: 'STRING',
    isRequired: true,
    description: 'Kode Objek',
  },
  {
    njfKey: 'JF_OBJT_ENGINE_NO',
    jsonKey: 'FUND_OBJT_ENGINE_NO',
    type: 'STRING',
    isRequired: true,
    description: 'Kode Mesin Objek',
  },
  {
    njfKey: 'JF_OBJT_GROUP_CODE',
    jsonKey: 'FUND_OBJT_GROUP',
    type: 'STRING',
    isRequired: true,
    description: 'Kode Group Objek',
  },
  {
    njfKey: 'JF_OBJT_PRICE',
    jsonKey: 'FUND_OBJT_PRICE',
    type: 'NUMBER',
    isRequired: true,
    description: 'Harga Object',
  },
  {
    njfKey: 'JF_OBJT_TYPE',
    jsonKey: 'FUND_OBJT_TYPE',
    type: 'STRING',
    isRequired: true,
    description: 'Kode Objek Type',
  },
  {
    njfKey: 'JF_OJK_CP',
    jsonKey: 'FUND_CARA_PEMBIAYAAN',
    type: 'STRING',
    isRequired: true,
    description: 'Cara Pembiayaan',
  },
  {
    njfKey: 'JF_OJK_KU',
    jsonKey: 'FUND_KEGIATAN_USAHA',
    type: 'STRING',
    isRequired: true,
    description: 'Kegiatan Usaha',
  },
  {
    njfKey: 'JF_PPD_DATE',
    jsonKey: 'FUND_PPD_DATE',
    type: 'DATE',
    isRequired: true,
    description: 'Tanggal PPD',
  },
  {
    njfKey: 'JF_PPD_NO',
    jsonKey: 'FUND_PPD_NO',
    type: 'STRING',
    isRequired: true,
    description: 'Nomor PPD',
  },
  {
    njfKey: 'JF_REASON',
    jsonKey: 'FUND_REASON',
    type: 'STRING',
    isRequired: true,
    description: 'Reason restructure',
  },
  {
    njfKey: 'JF_SALES_THROUGH',
    jsonKey: 'FUND_SALES_THROUGH',
    type: 'STRING',
    isRequired: true,
    description: 'Kode Sales Through (98,01,05)',
  },

  // Optional Fields (N)
  {
    njfKey: 'JF_ADMIN_FEE',
    jsonKey: 'FUND_UPP_ADM',
    type: 'NUMBER',
    isRequired: false,
    description: 'Up Admin',
  },
  {
    njfKey: 'JF_ADV_BENEFIT',
    jsonKey: 'FUND_ADV_BENEFIT',
    type: 'NUMBER',
    isRequired: false,
    description: 'Advance Benefit',
  },
  {
    njfKey: 'JF_ADV_INSF',
    jsonKey: 'FUND_ADV_INSF',
    type: 'NUMBER',
    isRequired: false,
    description: 'Insentif amount Adv',
  },
  {
    njfKey: 'JF_ASSIGN_TYPE',
    jsonKey: 'FUND_ASSIGN_TYPE',
    type: 'STRING',
    isRequired: false,
    description: 'Facility Type Pendanaan',
  },
  {
    njfKey: 'JF_BP_NASABAH',
    jsonKey: 'FUND_BP_NASABAH',
    type: 'STRING',
    isRequired: false,
    description: 'BP Nasabah',
  },
  {
    njfKey: 'JF_BPKB_STAT',
    jsonKey: 'FUND_BPKB_STAT',
    type: 'STRING',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_BRAND_DESC',
    jsonKey: 'FUND_BRAND_DESC',
    type: 'STRING',
    isRequired: false,
    description: 'Deskripsi brand',
  },
  {
    njfKey: 'JF_BUSINESS_SECTOR',
    jsonKey: 'FUND_BUSINESS_SECTOR',
    type: 'STRING',
    isRequired: false,
    description: 'Data Nasabah AM',
  },
  {
    njfKey: 'JF_CHANNEL',
    jsonKey: 'FUND_CHANNEL',
    type: 'STRING',
    isRequired: true,
    description: 'Channel AIT',
  },
  {
    njfKey: 'JF_CL_ID',
    jsonKey: 'FUND_CL_ID',
    type: 'STRING',
    isRequired: false,
    description: 'Type CL ID',
  },
  {
    njfKey: 'JF_COLA_STATUS',
    jsonKey: 'FUND_COLA_STATUS',
    type: 'STRING',
    isRequired: false,
    description: 'Kode Status Cola',
  },
  {
    njfKey: 'JF_COLA_TYPE',
    jsonKey: 'FUND_COLA_TYPE',
    type: 'STRING',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_COMM_AMT',
    jsonKey: 'FUND_COMM_AMT',
    type: 'NUMBER',
    isRequired: false,
    description: 'Amount Komisi',
  },
  {
    njfKey: 'JF_COMM_INSR',
    jsonKey: 'FUND_COMM_INSR',
    type: 'NUMBER',
    isRequired: false,
    description: 'Komisi Asuransi',
  },
  {
    njfKey: 'JF_CUST_ADDR',
    jsonKey: 'FUND_CUST_ADDR1',
    type: 'STRING',
    isRequired: false,
    description: 'Data Nasabah AM',
  },
  {
    njfKey: 'JF_CUST_ADDR2',
    jsonKey: 'FUND_CUST_ADDR2',
    type: 'STRING',
    isRequired: false,
    description: 'Data Nasabah AM',
  },
  {
    njfKey: 'JF_CUST_BIRTH_DATE',
    jsonKey: 'FUND_CUST_BIRTH',
    type: 'DATE',
    isRequired: false,
    description: 'Data Nasabah AM',
  },
  {
    njfKey: 'JF_CUST_CITY',
    jsonKey: 'FUND_CUST_CITY',
    type: 'STRING',
    isRequired: false,
    description: 'Data Nasabah AM',
  },
  {
    njfKey: 'JF_CUST_GENRE',
    jsonKey: 'FUND_CUST_GENRE',
    type: 'STRING',
    isRequired: false,
    description: 'Customer Genre DP (01 = Passenger, 02 = Commercial)',
  },
  {
    njfKey: 'JF_CUST_ID',
    jsonKey: 'FUND_CUST_OID',
    type: 'STRING',
    isRequired: false,
    description: 'Uniq Customer',
  },
  {
    njfKey: 'JF_CUST_KTP',
    jsonKey: 'FUND_KTP_NO',
    type: 'STRING',
    isRequired: false,
    description: 'Data Nasabah AM',
  },
  {
    njfKey: 'JF_CUST_NPWP',
    jsonKey: 'FUND_NPWP_NO',
    type: 'STRING',
    isRequired: false,
    description: 'Data Nasabah AM',
  },
  {
    njfKey: 'JF_CUST_OCCUPATION',
    jsonKey: 'CUST_OCCUPATION',
    type: 'STRING',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_CUST_TYPE',
    jsonKey: 'FUND_CUST_TYPE',
    type: 'STRING',
    isRequired: false,
    description: 'Tipe Customer (PER, COM)',
  },
  {
    njfKey: 'JF_DEAL_CODE',
    jsonKey: 'FUND_DEAL_CODE',
    type: 'STRING',
    isRequired: false,
    description: 'Kode Dealer',
  },
  {
    njfKey: 'JF_DEAL_COMM',
    jsonKey: 'FUND_DEAL_COMM',
    type: 'NUMBER',
    isRequired: false,
    description: 'Komisi Dealer',
  },
  {
    njfKey: 'JF_DEF_ADM',
    jsonKey: 'FUND_DEF_ADM',
    type: 'NUMBER',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_DESC',
    jsonKey: 'FUND_DESC',
    type: 'STRING',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_DP_GROSS',
    jsonKey: 'FUND_GROSS_DP',
    type: 'NUMBER',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_DP_NETT',
    jsonKey: 'FUND_NET_DP',
    type: 'NUMBER',
    isRequired: false,
    description: 'Minimal DP',
  },
  {
    njfKey: 'JF_DP_PERCENTAGE',
    jsonKey: 'FUND_DP_REAL',
    type: 'NUMBER',
    isRequired: false,
    description: 'Presentase DP Nasabah',
  },
  {
    njfKey: 'JF_DSR',
    jsonKey: 'DSR',
    type: 'STRING',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_FIN_TYPE',
    jsonKey: 'FUND_FIN_TYPE',
    type: 'NUMBER',
    isRequired: false,
    description: 'Flag Syariah/konven (1 Konven & 2 Syariah)',
  },
  {
    njfKey: 'JF_FLAG_INPUT',
    jsonKey: 'FUND_FLAG_INPUT',
    type: 'STRING',
    isRequired: false,
    description: 'Flaging Input',
  },
  {
    njfKey: 'JF_INSF_AMT',
    jsonKey: 'FUND_INSF_AMT',
    type: 'NUMBER',
    isRequired: false,
    description: 'Insentif amount',
  },
  {
    njfKey: 'JF_INSF_INSR',
    jsonKey: 'FUND_INSF_INSR',
    type: 'NUMBER',
    isRequired: false,
    description: 'Asuransi',
  },
  {
    njfKey: 'JF_INSR_EXT_TOP',
    jsonKey: 'FUND_INSR_EXT_TOP',
    type: 'NUMBER',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_INSR_NAME',
    jsonKey: 'FUND_INSR_NAME',
    type: 'STRING',
    isRequired: false,
    description: 'Nama Asuransi',
  },
  {
    njfKey: 'JF_INSR_TYPE',
    jsonKey: 'FUND_INSR_TYPE',
    type: 'STRING',
    isRequired: false,
    description: 'Tipe Asuransi Deskripsi',
  },
  {
    njfKey: 'JF_INSR_TYPE_DESC',
    jsonKey: 'FUND_INSR_TYPE_DESC',
    type: 'STRING',
    isRequired: false,
    description: 'Tipe Asuransi Deskripsi',
  },
  {
    njfKey: 'JF_INST_AMNT',
    jsonKey: 'FUND_ADMF_INST_AMT',
    type: 'NUMBER',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_INT_TYPE',
    jsonKey: 'FUND_INT_TYPE',
    type: 'STRING',
    isRequired: false,
    description: 'Jenis Kontrak (Annuity, Seasonal, Dclain-N, dll)',
  },
  {
    njfKey: 'JF_LEASE_TYPE',
    jsonKey: 'FUND_LEASE_TYPE',
    type: 'STRING',
    isRequired: false,
    description: 'Tipe Bank Pembiayaan',
  },
  {
    njfKey: 'JF_LTV',
    jsonKey: 'LTV',
    type: 'NUMBER',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_MKPP_ID',
    jsonKey: 'FUND_MKPP_ID',
    type: 'STRING',
    isRequired: false,
    description: 'Kode MKPP (PK Disaster DDR, DMR)',
  },
  {
    njfKey: 'JF_OBJT_ENGINE_CAPACITY',
    jsonKey: 'FUND_OBJT_ENGINE_CAPACITY',
    type: 'STRING',
    isRequired: false,
    description: 'Deskripsi Objek AM',
  },
  {
    njfKey: 'JF_OBJT_HAS_DOC',
    jsonKey: 'FUND_OBJT_DOC',
    type: 'STRING',
    isRequired: false,
    description: 'Object Document,  DOC Y (Flag : 1) = 10%, DOC N (Flag : 2) = 15%',
  },
  {
    njfKey: 'JF_OBJT_MODEL',
    jsonKey: 'FUND_OBJT_MODEL',
    type: 'STRING',
    isRequired: false,
    description: 'Kode Object Model',
  },
  {
    njfKey: 'JF_OBJT_OWNER_NAME',
    jsonKey: 'FUND_CUST_OWNER_NAME',
    type: 'STRING',
    isRequired: false,
    description: 'Pemilik Objek',
  },
  {
    njfKey: 'JF_OBJT_OWNER_NIK',
    jsonKey: 'FUND_CUST_OWNER_KTP_NO',
    type: 'STRING',
    isRequired: false,
    description: 'KTP Pemilik Objek',
  },
  {
    njfKey: 'JF_OBJT_OWNER_NPWP',
    jsonKey: 'FUND_CUST_OWNER_NPWP_NO',
    type: 'STRING',
    isRequired: false,
    description: 'NPWP Pemilik Objek',
  },
  {
    njfKey: 'JF_OBJT_PROD_YEAR',
    jsonKey: 'FUND_OBJT_PROD_YEAR',
    type: 'STRING',
    isRequired: false,
    description: 'Tahun Objek',
  },
  {
    njfKey: 'JF_OBJT_PURPOSE',
    jsonKey: 'FUND_OBJT_PURPOSE',
    type: 'STRING',
    isRequired: false,
    description:
      'DP_OBJT_PURPOSE JIKA 0 MAKA OBJECT DOC TIDAK PERNAH 1 (PROPOSE NON PRODUCTIVE), DP_OBJT_PURPOSE JIKA 1 MAKA OBJECT DOC BISA 1 & 0 (PROPOSE PRODUCTIVE)',
  },
  {
    njfKey: 'JF_OBJT_YEAR',
    jsonKey: 'FUND_OBJT_YEAR',
    type: 'STRING',
    isRequired: false,
    description: 'Tahun Objek',
  },
  {
    njfKey: 'JF_OLD_CONT_NO',
    jsonKey: 'FUND_OLD_CONT_NO',
    type: 'STRING',
    isRequired: false,
    description: 'Terisi khusus untuk PK baru restructure (diisi no PK lama)',
  },
  {
    njfKey: 'JF_PAY_TYPE',
    jsonKey: 'FUND_PAY_TYPE',
    type: 'STRING',
    isRequired: false,
    description: 'Tipe Pembayaran (Kasir, Kolektor, Bank, Revolving dan Non Revolving )',
  },
  {
    njfKey: 'JF_PORTFOLIO',
    jsonKey: 'FUND_PORTFOLIO',
    type: 'STRING',
    isRequired: true,
    description: 'Portofolio Jurnal',
  },
  {
    njfKey: 'JF_PRODUCT_ID',
    jsonKey: 'FUND_PRODUCT_ID',
    type: 'STRING',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_PRODUCT_MATRIX',
    jsonKey: 'FUND_PRODUCT_MATRIX',
    type: 'STRING',
    isRequired: true,
    description: 'Kode Product Metrix',
  },
  {
    njfKey: 'JF_PROGRAM',
    jsonKey: 'FUND_PROGRAM',
    type: 'STRING',
    isRequired: false,
    description: 'Tipe Program',
  },
  {
    njfKey: 'JF_PROV_AMT',
    jsonKey: 'FUND_PROV_AMT',
    type: 'NUMBER',
    isRequired: false,
    description: 'Provisi Amount',
  },
  {
    njfKey: 'JF_REGION_CODE',
    jsonKey: 'FUND_REGION_ID',
    type: 'STRING',
    isRequired: false,
    description: 'ID Region',
  },
  {
    njfKey: 'JF_REHAB_TYPE',
    jsonKey: 'FUND_REHAB_TYPE',
    type: 'STRING',
    isRequired: false,
    description: 'Tipe Restucture',
  },
  {
    njfKey: 'JF_REJF_PROV',
    jsonKey: 'FUND_REFUND_PROV',
    type: 'NUMBER',
    isRequired: false,
    description: 'Pengembalian Provisi',
  },
  {
    njfKey: 'JF_RESCHD_TYPE',
    jsonKey: 'FUND_RESCHD_TYPE',
    type: 'STRING',
    isRequired: false,
    description: 'Status Kontrak Reschedule',
  },
  {
    njfKey: 'JF_SUBS_AMT',
    jsonKey: 'FUND_SUBS_AMT',
    type: 'NUMBER',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_SUBT_FIDS',
    jsonKey: 'FUND_SUBT_FIDS',
    type: 'NUMBER',
    isRequired: false,
    description: '?',
  },
  {
    njfKey: 'JF_TYPE_DESC',
    jsonKey: 'FUND_TYPE_DESC',
    type: 'STRING',
    isRequired: false,
    description: 'Tipe Deskripsi',
  },
  {
    njfKey: 'JF_UPP_INTR',
    jsonKey: 'FUND_UPP_INTR',
    type: 'NUMBER',
    isRequired: false,
    description: 'upping interest',
  },
]
